// ERC-8021 Builder Code Attribution
//
// Uses the `ox` library to generate a proper ERC-8021 Schema 2 dataSuffix
// that appends Signet's builder code to every transaction on Base.
//
// Registered via: POST https://api.base.dev/v1/agents/builder-codes
// Wallet: 0x3b4EcE4CdE860e0A9076f70483Db3e4209CC1175
// Builder Code: bc_2jqg6gik
//
// Per Base docs: never send a transaction without attribution.
// Missing attribution = silent data loss, no errors, no warnings.

import { Attribution } from 'ox/erc8021';

/** Real builder code registered at api.base.dev */
export const SIGIL_BUILDER_CODE = 'bc_2jqg6gik';

/**
 * ERC-8021 dataSuffix generated by the `ox` library.
 * Append this to all transaction calldata on Base.
 */
export const DATA_SUFFIX = Attribution.toDataSuffix({
  codes: [SIGIL_BUILDER_CODE],
});

/**
 * Get the ERC-8021 dataSuffix for Base transaction attribution.
 * For x402 payments, the x402 layer handles attribution separately.
 * This is for non-x402 transactions (EAS attestations, contract calls, etc.)
 */
export function getAttributionDataSuffix(): string {
  return DATA_SUFFIX;
}